services:
  server:
    image: yehor542/socket_messenger_server
    env_file:
      - ./server/.env


  client:
    image: yehor542/socket_messenger_client
    env_file:
      - ./client/.env
    depends_on:
      - server
    stdin_open: true #same as -it flags
    tty: true
    command: sleep infinity
