services:
  server:
    build: ./server/
    env_file:
      - ./server/.env


  client:
    build: ./client/
    env_file:
      - ./client/.env
    depends_on:
      - server
    stdin_open: true #same as -it flags
    tty: true
    command: sleep infinity
